language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - pytest -v -s
  - pwd
  - ls -al CsClass/
  - find CsClass/ -type f -exec cat {} +
  - ls -al Controllers/
  - find Controllers/ -type f -exec cat {} +
